name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag ubuntu22.04-luke --file dockerfile .
    - name: Build the Docker container
      run: docker compose --file compose.yml up --detach
    - name: Run the actual command
      run: docker exec -t ubuntu-lukesmith make
    - name: Show me what you got
      run: ls -alh
