name: GitHub Self-Updating Repository Demo
# changes ddfdd
on: [push]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v3.0.2
        uses: actions/checkout@v3
      - name: Clear README and set text
        run: |
          cat README.md
          echo "# What is Today's Date?" > README.md
          echo "This repository keeps track of today's date." >> README.md
          echo "* * *" >> README.md
          echo " " >> README.md
          echo "## The current date:  " >> README.md
      - name: Modify date and time
        run: |
          cat README.md
          echo " $(date +"%m/%d/%Y") " >> README.md
          cat README.md
      - name: Push to repository
        run: |
          git config --global user.name "ToddServo"
          git config --global user.email "16764933+ToddServo@users.noreply.github.com"
          now=$(date)
          git add -A
          git commit -m "Auto Push on $now"
          git push
